spring:
  freemarker:
    cache: false
    suffix: .html
    charset: UTF-8
    template-loader-path: classpath:/templates/
  security:
    logintype: JSON
server:
  servlet:
    session:
      cookie:
        http-only: true
#        secure: true