spring:
  #配置数据源
  datasource:
    name: quartz
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1pmj8cpzd51eqb5ho.mysql.rds.aliyuncs.com:3306/quartz?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: zhangchun
    password: zc123123
  quartz:
    #持久化到数据库方式
    job-store-type: jdbc
    initialize-schema: embedded
    properties:
      org:
        quartz:
          scheduler:
            instanceName: scheduler
            instanceId: AUTO
          jobStore:
            dataSource: quartz
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
#          dataSource:
#            quartz:
#              driver: com.mysql.jdbc.Driver
#              URL: jdbc:mysql://rm-bp1pmj8cpzd51eqb5ho.mysql.rds.aliyuncs.com:3306/quartz?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
#              username: zhangchun
#              password: zc123123
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true