server:
  port: 8080
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  config: classpath:log4j2.xml
jwt:
  header: JWTHeaderName
  secret: aabbccdd
  expiration: 360000
