spring:
  datasource:
    url: jdbc:mysql://eshop-cache04:3306/feature
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: zc123123
  freemarker:
    cache: false
    suffix: .html
    charset: UTF-8
    template-loader-path: classpath:/templates/
  security:
    logintype: JSON

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml